# coding: utf-8

"""
    Pet Store API

    A simple pet store API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pets_post_request import PetsPostRequest

class TestPetsPostRequest(unittest.TestCase):
    """PetsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetsPostRequest:
        """Test PetsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetsPostRequest`
        """
        model = PetsPostRequest()
        if include_optional:
            return PetsPostRequest(
                name = ''
            )
        else:
            return PetsPostRequest(
        )
        """

    def testPetsPostRequest(self):
        """Test PetsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
