# coding: utf-8

"""
    Pet Store API

    A simple pet store API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pets_get200_response_inner import PetsGet200ResponseInner

class TestPetsGet200ResponseInner(unittest.TestCase):
    """PetsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetsGet200ResponseInner:
        """Test PetsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetsGet200ResponseInner`
        """
        model = PetsGet200ResponseInner()
        if include_optional:
            return PetsGet200ResponseInner(
                id = 56,
                name = ''
            )
        else:
            return PetsGet200ResponseInner(
        )
        """

    def testPetsGet200ResponseInner(self):
        """Test PetsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
